### PR TITLE
Feature/add private key support for ethereum

### PR DESCRIPTION
**Pull request by saadibrahim**
mnenomic cannot be derived from a privateKey so you will see that its null, there are no side effects to this.

### CODE REVIEW

**Comment by saadibrahim** [comment]
Sorry, I realized I should add tests for this, I will handle this on Monday but you can take a look at this.

**Comment by saadibrahim** [comment]
Done, made the changes. ready to be reviewed @tahpot

**Review by tahpot — APPROVED** [review]
Thanks @saadibrahim 

Approved.

I assume you will need to do the same for the other supported chains?

**Comment by saadibrahim** [comment]
@tahpot we wont be doing this for other chains as other chains do not have private key based import (only seedphrase), private key import is limited to EVM chains to make it compatible with how metamask exports. Other chains dont need this, for example algorand native wallet only exports the 25 word mnemonic.

I came to this conclusion after doing through other wallets:

https://github.com/verida/vault-mobile/issues/484#issuecomment-1227289790

**Pull request merged**
